// tools/inventory.mjs — ranked inventory across every OPEN-ISSUES.md ledger.
//
// Pure functions over text; the CLI at the bottom does the only I/O. Ranking is
// declared per entry (`- rank:`), never inferred here: a tool that guesses a
// priority produces a confidently wrong ordering, which is the one thing this
// file exists to prevent.

import { readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HEADING = /^##\s+(OI-\d+)\s+(?:\[([^\]]+)\]\s*)?(.*)$/;
const FIELD = /^-\s+([a-z-]+):\s*(.*)$/i;

export function parseLedger(text, ledger) {
  const entries = [];
  let cur = null;
  for (const line of text.split(/\r?\n/)) {
    const h = HEADING.exec(line);
    if (h) {
      cur = {
        id: h[1],
        qualifiedId: `${ledger}#${h[1]}`,
        ledger,
        title: h[3].trim(),
        marker: h[2] ?? null,
        fields: {},
      };
      entries.push(cur);
      continue;
    }
    if (!cur) continue;
    const f = FIELD.exec(line);
    if (f) cur.fields[f[1].toLowerCase()] = f[2].trim();
  }
  return entries;
}

// SHRUNK is deliberately absent: a shrunk entry is a smaller open entry, not a
// closed one. OI-015 has been marked SHRUNK and unfinished since 2026-08-04.
const CLOSED = /^(RESOLVED|RETIRED|SUPERSEDED)\b/;

export function isOpen(entry) {
  return !(entry.marker && CLOSED.test(entry.marker));
}

// Kyle's priority order, verbatim from his 2026-08-04 prompt. Closed set: an
// unknown value is a typo in a ledger, and coercing it to a default would hide
// the typo behind a plausible ordering.
export const RANKS = Object.freeze([
  "safety", "broken-workflow", "data-loss", "autonomy-blocker", "reliability",
  "control", "usability", "maintainability", "performance", "roi",
]);

export function rankOrdinal(entry) {
  const r = entry.fields.rank;
  if (!r) return -1;
  const i = RANKS.indexOf(r);
  if (i === -1) throw new Error(`unknown rank "${r}" on ${entry.qualifiedId}`);
  return i;
}

const idNum = (e) => Number(e.id.slice(3));

export function sortEntries(entries) {
  return [...entries].sort((a, b) => {
    const ra = rankOrdinal(a), rb = rankOrdinal(b);
    if (ra !== rb) return ra - rb;          // -1 (unranked) sorts first
    if (a.ledger !== b.ledger) return a.ledger < b.ledger ? -1 : 1;
    return idNum(a) - idNum(b);
  });
}

// Dedup is DECLARED, never inferred. Kyle's prompt says deduplicate "without
// losing any requirements"; a title-similarity heuristic silently drops one
// side's requirements, which is the exact loss it must not cause.
export function dedupe(entries) {
  const byQid = new Map(entries.map((e) => [e.qualifiedId, e]));
  const rows = new Map();
  const dupes = [];
  for (const e of entries) {
    const target = e.fields["duplicate-of"];
    if (target) {
      if (!byQid.has(target)) {
        throw new Error(`${e.qualifiedId} is duplicate-of ${target} — ${target} does not exist`);
      }
      dupes.push([e, target]);
    } else {
      rows.set(e.qualifiedId, { ...e, ids: [e.qualifiedId] });
    }
  }
  for (const [e, target] of dupes) {
    const row = rows.get(target);
    if (!row) throw new Error(`${e.qualifiedId} is duplicate-of ${target}, which is itself a duplicate`);
    row.ids.push(e.qualifiedId);
  }
  return [...rows.values()];
}

const rankOf = (r) => (r.fields.rank ? r.fields.rank : "UNRANKED");

export function toJson(rows, meta) {
  return {
    generatedFrom: meta.generatedFrom,
    rows: sortEntries(rows).map((r) => ({
      ids: r.ids,
      ledger: r.ledger,
      title: r.title,
      rank: rankOf(r),
      marker: r.marker,
    })),
  };
}

export function toMarkdown(rows, meta) {
  const lines = [
    "# Open work — ranked inventory",
    "",
    "> This file is generated by `tools/inventory.mjs`; do not hand-edit.",
    `> Generated from commit \`${meta.generatedFrom}\`.`,
    "",
    "| # | Rank | Ids | Ledger | Title |",
    "|---|---|---|---|---|",
  ];
  sortEntries(rows).forEach((r, i) => {
    lines.push(`| ${i + 1} | ${rankOf(r)} | ${r.ids.join(", ")} | ${r.ledger} | ${r.title} |`);
  });
  lines.push("");
  return lines.join("\n");
}

export function run(argv, io) {
  const all = io.ledgers.flatMap((l) => parseLedger(io.readFile(l.path), l.name));
  const open = all.filter(isOpen);

  if (argv.includes("--check")) {
    const unranked = open.filter((e) => !e.fields.rank);
    if (unranked.length === 0) return { code: 0, stdout: "inventory: every open entry is ranked\n" };
    const list = unranked.map((e) => `  UNRANKED ${e.qualifiedId} ${e.title}`).join("\n");
    return { code: 1, stdout: `inventory: ${unranked.length} open entr(ies) have no rank:\n${list}\n` };
  }

  const rows = dedupe(open);
  const meta = { generatedFrom: io.commit };
  return {
    code: 0,
    stdout: argv.includes("--json")
      ? JSON.stringify(toJson(rows, meta), null, 2)
      : toMarkdown(rows, meta),
  };
}

// The guards ledger and this repo's own commit are resolved relative to
// THIS file's own checkout, not a hardcoded C:/code/guards, so the CLI
// reports the running worktree's own state (branch, uncommitted ranks)
// instead of whatever happens to be checked out at the canonical path —
// load-bearing while sub-projects run one-worktree-per-branch (the
// completion plan's own convention).
const REPO_ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

export function realIo() {
  return {
    readFile: (p) => readFileSync(p, "utf8"),
    ledgers: [
      { name: "code", path: "C:/code/OPEN-ISSUES.md" },
      { name: "guards", path: path.join(REPO_ROOT, "OPEN-ISSUES.md") },
      { name: "ecosystem", path: "C:/code/lifeos-ecosystem/OPEN-ISSUES.md" },
      { name: "lifeos", path: "C:/code/lifeos-ecosystem/lifeos/OPEN-ISSUES.md" },
      { name: "lifeos-ui", path: "C:/code/lifeos-ecosystem/lifeos-ui/OPEN-ISSUES.md" },
    ],
    commit: execFileSync("git", ["rev-parse", "--short", "HEAD"], {
      cwd: REPO_ROOT, encoding: "utf8",
    }).trim(),
  };
}

// Exported and called directly by tests, in-process — a spawned subprocess is
// invisible to this file's own coverage instrumentation (same fix already
// applied to hooks/goal.mjs for OI-006). Returns the exit code rather than
// calling process.exit itself, so a test can call this without killing the
// test runner.
export function main(argv = process.argv.slice(2)) {
  const r = run(argv, realIo());
  process.stdout.write(r.stdout);
  return r.code;
}

// Real CLI entry point. Windows note: import.meta.url is `file:///C:/...`
// (triple slash); comparing it directly against a `file://${argv[1]}`
// template string never matches on Windows. Resolve both sides to plain
// paths instead, matching the idiom this repo already uses
// (hooks/covgate.mjs:243, hooks/goal.mjs:456).
if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) process.exit(main());
