// node --test tools/inventory.test.mjs   (run from the repo root)
//
// Hermetic: every case is an inline ledger fragment. Only Task 9 reads the
// real ledgers on disk.
import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";

const m = await import("./inventory.mjs");

const ONE_ENTRY = `# Open issues

## OI-034 A console PID is treated as a console IDENTITY
- opened: 2026-08-04
- rank: reliability
- where: core/standing.mjs
- what: liveness is a bare process.kill(pid, 0) existence test.
`;

test("parses id, qualified id, title and fields from one entry", () => {
  const [e] = m.parseLedger(ONE_ENTRY, "guards");
  assert.equal(e.id, "OI-034");
  assert.equal(e.qualifiedId, "guards#OI-034");
  assert.equal(e.ledger, "guards");
  assert.equal(e.title, "A console PID is treated as a console IDENTITY");
  assert.equal(e.marker, null);
  assert.equal(e.fields.rank, "reliability");
  assert.equal(e.fields.opened, "2026-08-04");
});

const MARKERS = `
## OI-001 [RESOLVED 2026-08-03] done thing
- rank: reliability
## OI-002 [RETIRED 2026-08-04] not doing it
- rank: roi
## OI-003 [SUPERSEDED 2026-08-03] replaced
- rank: roi
## OI-015 [SHRUNK — needs Kyle for the rest] half done
- rank: control
## OI-034 still open
- rank: reliability
`;

test("RESOLVED, RETIRED and SUPERSEDED close an entry; SHRUNK does not", () => {
  const open = m.parseLedger(MARKERS, "guards").filter(m.isOpen).map((e) => e.id);
  assert.deepEqual(open, ["OI-015", "OI-034"]);
});

test("entries sort by rank ordinal, then ledger, then id", () => {
  const es = m.parseLedger(`
## OI-009 later id
- rank: safety
## OI-002 low priority
- rank: roi
## OI-001 high priority
- rank: safety
`, "guards");
  assert.deepEqual(m.sortEntries(es).map((e) => e.id), ["OI-001", "OI-009", "OI-002"]);
});

test("an entry with no rank is UNRANKED and sorts first", () => {
  const es = m.parseLedger(`
## OI-001 ranked
- rank: safety
## OI-002 unranked
- opened: 2026-08-04
`, "guards");
  const sorted = m.sortEntries(es);
  assert.equal(sorted[0].id, "OI-002");
  assert.equal(m.rankOrdinal(sorted[0]), -1);
});

test("an unknown rank value fails loudly instead of defaulting", () => {
  const [e] = m.parseLedger("## OI-001 t\n- rank: urgent\n", "guards");
  assert.throws(() => m.rankOrdinal(e), /unknown rank "urgent"/);
});

test("duplicate-of collapses entries into one row listing every id", () => {
  const a = m.parseLedger("## OI-031 reaping\n- rank: reliability\n", "guards");
  const b = m.parseLedger(
    "## OI-007 same thing\n- rank: reliability\n- duplicate-of: guards#OI-031\n", "code");
  const rows = m.dedupe([...a, ...b]);
  assert.equal(rows.length, 1);
  assert.deepEqual(rows[0].ids, ["guards#OI-031", "code#OI-007"]);
});

test("duplicate-of naming a nonexistent id fails the run", () => {
  const es = m.parseLedger("## OI-007 t\n- rank: roi\n- duplicate-of: guards#OI-999\n", "code");
  assert.throws(() => m.dedupe(es), /guards#OI-999 does not exist/);
});

test("identical ids in different ledgers never collide", () => {
  const es = [
    ...m.parseLedger("## OI-001 guards one\n- rank: safety\n", "guards"),
    ...m.parseLedger("## OI-001 lifeos one\n- rank: safety\n", "lifeos"),
  ];
  assert.equal(m.dedupe(es).length, 2);
});

// Property, not example: three hand-picked rows would not catch an emitter that
// drops rows past a certain count or mangles a character class.
function generateLedger(seed, count) {
  let s = seed;
  const rnd = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
  let out = "";
  for (let i = 1; i <= count; i++) {
    const rank = m.RANKS[Math.floor(rnd() * m.RANKS.length)];
    out += `## OI-${String(i).padStart(3, "0")} title ${Math.floor(rnd() * 1e6)}\n- rank: ${rank}\n`;
  }
  return out;
}

test("JSON and Markdown carry identical data for any generated ledger", () => {
  for (const seed of [1, 7, 99, 12345]) {
    const rows = m.dedupe(m.parseLedger(generateLedger(seed, 40), "guards"));
    const meta = { generatedFrom: "abc1234" };
    const json = m.toJson(rows, meta);
    const md = m.toMarkdown(rows, meta);
    assert.equal(json.rows.length, rows.length, `seed ${seed}: row count`);
    for (const r of json.rows) {
      assert.ok(md.includes(r.ids[0]), `seed ${seed}: ${r.ids[0]} missing from markdown`);
      assert.ok(md.includes(r.title), `seed ${seed}: title missing from markdown`);
      assert.ok(md.includes(r.rank), `seed ${seed}: rank missing from markdown`);
    }
  }
});

test("the generated markdown says it is generated and records the commit", () => {
  const rows = m.dedupe(m.parseLedger("## OI-001 t\n- rank: safety\n", "guards"));
  const md = m.toMarkdown(rows, { generatedFrom: "deadbee" });
  assert.match(md, /generated by `tools\/inventory\.mjs`/);
  assert.match(md, /do not hand-edit/i);
  assert.match(md, /deadbee/);
});

const io = (files) => ({
  readFile: (p) => files[p],
  ledgers: Object.keys(files).map((p) => ({ name: p.replace(/\W/g, ""), path: p })),
  commit: "abc1234",
});

test("--check exits 1 and names every unranked open entry", () => {
  const r = m.run(["--check"], io({
    "a.md": "## OI-001 ranked\n- rank: safety\n## OI-002 not ranked\n- opened: x\n",
  }));
  assert.equal(r.code, 1);
  assert.match(r.stdout, /UNRANKED/);
  assert.match(r.stdout, /OI-002/);
  assert.doesNotMatch(r.stdout, /OI-001/);
});

test("--check exits 0 when every open entry is ranked", () => {
  const r = m.run(["--check"], io({ "a.md": "## OI-001 t\n- rank: safety\n" }));
  assert.equal(r.code, 0);
});

test("--check ignores closed entries", () => {
  const r = m.run(["--check"], io({
    "a.md": "## OI-001 [RESOLVED 2026-08-04] done\n- opened: x\n",
  }));
  assert.equal(r.code, 0);
});

test("--json emits parseable JSON with the commit stamp", () => {
  const r = m.run(["--json"], io({ "a.md": "## OI-001 t\n- rank: safety\n" }));
  assert.equal(r.code, 0);
  assert.equal(JSON.parse(r.stdout).generatedFrom, "abc1234");
});

// Real-ledger integration, via the real io the CLI itself builds
// (m.realIo()) — guards resolves relative to THIS repo's own checkout
// (whichever worktree is running), matching the CLI's own REPO_ROOT-relative
// resolution, so this also exercises realIo()'s own lines for coverage
// instead of duplicating a second hardcoded ledger list here.
const haveAll = m.realIo().ledgers.every((l) => fs.existsSync(l.path));

test("every open entry in all five real ledgers is ranked", { skip: !haveAll }, () => {
  const r = m.run(["--check"], m.realIo());
  assert.equal(r.code, 0, r.stdout);
});

test("the real ledgers parse and rank without throwing", { skip: !haveAll }, () => {
  const r = m.run(["--json"], m.realIo());
  assert.equal(r.code, 0);
  const j = JSON.parse(r.stdout);
  assert.ok(j.rows.length > 0);
  assert.ok(j.rows.every((row) => row.rank !== "UNRANKED"));
});

// main() is a spawned subprocess's entry point in real use, invisible to this
// file's own coverage instrumentation when spawned — so it's called directly,
// in-process, the same way core/standing.test.mjs exercises core/standing.mjs's
// exported main(). It writes real stdout as a side effect; that's expected.
test("main() runs --check against the real ledgers and returns run()'s exit code", { skip: !haveAll }, () => {
  assert.equal(m.main(["--check"]), 0);
});

test("every Definition-of-Done condition maps to a real ledger id or spec AC", () => {
  const map = fs.readFileSync("docs/dod-mapping.md", "utf8");
  const rows = map.split("\n").filter((l) => /^\|\s*\d+\s*\|/.test(l));
  assert.equal(rows.length, 22, "all 22 conditions must be listed");
  for (const row of rows) {
    const covered = row.split("|")[3].trim();
    assert.notEqual(covered, "", `row has no coverage: ${row}`);
    assert.doesNotMatch(covered, /^(TBD|TODO|-|\?)$/i, `row has a placeholder coverage: ${row}`);
  }
});
